---
title: "Google Data Analytics Specialization - CapStone Project"
author: "Hartmut Schaefer"
date: "2023-03-27"
output: 
  html_document:
    toc: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\
\

# Case study: Cyclistic
\


##  Contents

This website contains  two approaches to the data analysis case study project from start to end:\
\

- **Project 1:** data cleaning in SQL/ data analysis in Tableau\
  -- This was my first approach within the course. Its focus was on big data wrangling and quick visualization in Tableau\
  -- The data selection and cleaning process was later revised to be comparable with the 2nd project\
\

- **Project 2:** data cleaning and data analysis in R\
  -- This was my second approach using R and is going a little bit deeper\
  -- Some statistics has been applied to find significant outliers and correlations\
\

All steps are documents in R Markdown including SQL and R codes. All codes are executable from the R Markdown documents under the condition that the data are downloaded and a connection to the SQL Server is established.\

The analysis in Tableau is only documented in screenshots. The original dashboards and story point are available in [Tableau Public](https://public.tableau.com/app/profile/hartmut.schaefer/viz/Bike-ShareCaseStudy-GoogleDataAnalyticsCapStoneProject/Cyclistics-StoryPoint).\
\
\

**Links to documents:**\
\

### [> Introduction](introduction.html)\

### [> Project in SQL and Tableau](project1.html)\

### [> Project in R](project2.html)\
\







